spring.application.name=bpm

# Configuration des URLs des APIs Node.js
api.node.assurance.url=http://localhost:3001/api/assurances
api.node.notification.url=http://localhost:3001/api/notifications

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/bpm
spring.datasource.username=postgres
spring.datasource.password=tiga tiga
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




